[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "JazLabs"
version = "0.1.0"
description = "JazLabs is a playground for building experiments and bringing different instruments together like jazz."
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "opencv-python",
    "pyzmq",
    "Pillow",
    "numexpr",
    "numba",
    "screeninfo",
]

[project.optional-dependencies]
notebooks = [
    "ipython",
    "ipykernel",
    "jupyter",
    "ipywidgets",
]
serial = [
    "pyserial",
]
visa = [
    "pyvisa",
]
ni = [
    "nidaqmx",
]
zaber = [
    "zaber-motion",
]
optimization = [
    "cma",
]
powermeters = [
    "ThorlabsPM100",
]
all-pip = [
    "ipython",
    "ipykernel",
    "jupyter",
    "ipywidgets",
    "pyserial",
    "pyvisa",
    "nidaqmx",
    "zaber-motion",
    "cma",
    "ThorlabsPM100",
]

[project.scripts]
jazlabs-server-camera = "JazLabs.launchers.launch_camera_server:main"
jazlabs-server-laser = "JazLabs.launchers.launch_laser_server:main"
jazlabs-server-daq = "JazLabs.launchers.launch_daq_server:main"
jazlabs-server-optical-switch = "JazLabs.launchers.launch_optical_switch_server:main"
jazlabs-server-slm-linux = "JazLabs.launchers.launch_slm_linux_server:main"
jazlabs-server-slm-windows = "JazLabs.launchers.launch_slm_windows_server:main"
jazlabs-server-slm-stack = "JazLabs.launchers.launch_slm_stack_server:main"
jazlabs-bridge-camera = "JazLabs.launchers.launch_camera_bridge:main"
jazlabs-bridge-daq = "JazLabs.launchers.launch_daq_bridge:main"
jazlabs-tmux = "JazLabs.launchers.tmux:main"
jazlabs-view = "JazLabs.launchers.launch_viewers:main"
jazlabs-view-camera = "JazLabs.launchers.launch_camera_viewer:main"
jazlabs-view-spot-power = "JazLabs.launchers.launch_spot_power_viewer:main"
jazlabs-view-laser = "JazLabs.launchers.launch_laser_widget:main"
jazlabs-view-optical-switch = "JazLabs.launchers.launch_optical_switch_widget:main"
jazlabs-view-slm = "JazLabs.launchers.launch_slm_viewer:main"
jazlabs-view-slm-stack = "JazLabs.launchers.launch_slm_stack_viewer:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
